---
- name: Playbook With Vault
  hosts: all
  become: true
  tasks:
    - name: include vault
      ansible.builtin.include_vars:
       file: mypassword.yml

    - name: print variable
      ansible.builtin.debug:
       var: mypassword
